INSERT INTO SanPham
    (
    ma_san_pham,
    ten_san_pham,
    gia_nhap,
    gia_xuat,
    trong_luong,
    ma_kich_thuoc,
    gioi_tinh,
    so_luong,
    don_vi_tinh,
    trang_thai,
    mo_ta,
    ngay_tao,
    ngay_chinh_sua,
    hinh_anh,
    ma_danh_muc,
    loai_san_pham,
    bo_suu_tap,
    thuong_hieu
    )
VALUES
    -- DANH MUC 2 - LOAI 1
    (
        1,
        'Vòng Tay Pandora Bạc Xoắn Xanh Dương',
        3000000,
        3390000,
        10.40,
        17,
        1,
        30,
        'chiếc',
        1,
        'Thể hiện gu thẩm mỹ tinh tế và độc đáo với Vòng Tay Pandora Bạc Xoắn Xanh Dương. Thiết kế dây xích hộp bạc sterling kết hợp dải màu xanh ngọc lam mang vẻ đẹp hiện đại và phóng khoáng.',
        NOW(), NOW(), NULL, 2, 1, 11, 2),
    (
        2,
        'Vòng Bạc Pandora Moments Dây Mềm Khóa Tròn',
        2000000,
        2390000,
        8.40,
        17,
        1,
        40,
        'chiếc',
        1,
        'Khởi đầu câu chuyện Pandora của bạn với vòng Moments dây mềm khóa tròn. Thiết kế tinh giản, lý tưởng để phối cùng các charm yêu thích.',
        NOW(), NOW(), NULL, 2, 1, 11, 2),
    -- DANH MUC 2 - LOAI 2
    (
        3,
        'Vòng Tay Khóa Tròn Mạ Vàng 14K Dây Da Màu Đỏ',
        3000000,
        3213000,
        7.50,
        17,
        1,
        20,
        'chiếc',
        1,
        'Vòng tay Pandora dây da màu đỏ kết hợp khóa tròn mạ vàng 14K sang trọng, biểu tượng cho phong cách hiện đại và cá tính.',
        NOW(), NOW(), NULL, 2, 2, 12, 2),
    (
        4,
        'Vòng Tay Bạc Khóa Tròn Dây Da Xanh',
        1200000,
        1095000,
        7.20,
        17,
        1,
        30,
        'chiếc',
        1,
        'Vòng tay Pandora bạc 925 với khóa tròn đặc trưng kết hợp dây da xanh thanh lịch, dễ phối đồ.',
        NOW(), NOW(), NULL, 2, 2, 12, 2),
    (
        5,
        'Vòng Tay Pandora Dây Da Đôi Khóa Móc Màu Nâu',
        2700000,
        2990000,
        8.00,
        17,
        1,
        15,
        'chiếc',
        1,
        'Vòng tay Pandora dây da đôi màu nâu, khóa móc kim loại chắc chắn, phong cách mạnh mẽ và hiện đại.',
        NOW(), NOW(), NULL, 2, 2, 12, 2),
    -- DANH MUC 2 - LOAI 3
    (
        6,
        'Vòng Tay Tennis Bạc Trái Tim Đính Đá Trong Suốt',
        4200000,
        4590000,
        6.80,
        17,
        1,
        20,
        'chiếc',
        1,
        'Vòng tay tennis bạc 925 với chi tiết trái tim đính đá trong suốt, thiết kế nữ tính và thanh lịch.',
        NOW(), NOW(), NULL, 2, 3, 13, 2),
    (
        7,
        'Vòng Tay Pandora Timeless Tennis Bạc Đính Đá',
        4300000,
        4590000,
        6.90,
        17,
        1,
        25,
        'chiếc',
        1,
        'Vòng tay Pandora Timeless phong cách tennis với hàng đá zirconia đính đều tinh xảo.',
        NOW(), NOW(), NULL, 2, 3, 13, 2),
    (
        8,
        'Vòng Tay Tennis Mạ Vàng Hồng 14K Trái Tim Đính Đá',
        6500000,
        6990000,
        7.10,
        17,
        1,
        15,
        'chiếc',
        1,
        'Vòng tay tennis mạ vàng hồng 14K nổi bật với chi tiết trái tim đính đá sang trọng.',
        NOW(), NOW(), NULL, 2, 3, 13, 2),
    (
        9,
        'Vòng Bạc Pandora Mắt Xích Cài',
        2500000,
        2790000,
        8.50,
        17,
        1,
        20,
        'chiếc',
        1,
        'Vòng tay bạc Pandora thiết kế mắt xích bản lớn, khóa cài chắc chắn, phong cách cá tính.',
        NOW(), NOW(), NULL, 2, 3, 13, 2),
    (
        10,
        'Vòng Tay Pandora Timeless Khóa Tròn Halo Đính Đá',
        4200000,
        4590000,
        6.70,
        17,
        1,
        20,
        'chiếc',
        1,
        'Vòng tay Pandora Timeless với khóa tròn Halo đính đá lấp lánh, tinh tế và sang trọng.',
        NOW(), NOW(), NULL, 2, 3, 13, 2),
    (
        11,
        'Vòng Bạc Pandora Mắt Xích Khóa Trượt Đính Đá',
        2500000,
        2790000,
        8.30,
        17,
        1,
        15,
        'chiếc',
        1,
        'Vòng tay bạc Pandora dạng mắt xích kết hợp khóa trượt đính đá, dễ điều chỉnh kích thước.',
        NOW(), NOW(), NULL, 2, 3, 13, 2),
    (
        12,
        'Vòng Kiềng Mạ Vàng 14K Khóa Trái Tim Đan Nhau',
        8000000,
        8690000,
        8.10,
        17,
        1,
        25,
        'chiếc',
        1,
        'Vòng kiềng mạ vàng 14K với khóa trái tim đan nhau, biểu tượng cho sự gắn kết và tình yêu vĩnh cửu.',
        NOW(), NOW(), NULL, 2, 4, 11, 2),
    (
        13,
        'Vòng Kiềng Pandora Signature Mạ Vàng Hồng 14K',
        7900000,
        8490000,
        9.90,
        17,
        1,
        20,
        'chiếc',
        1,
        'Vòng kiềng Pandora Signature mạ vàng hồng 14K, thiết kế nửa vuông nửa tròn độc đáo, hoàn thiện thủ công tinh xảo.',
        NOW(), NOW(), NULL, 2, 4, 12, 2),
    (
        14,
        'Charm Treo Trái Tim Pandora Moments',
        900000,
        1190000,
        2.10,
        17,
        1,
        50,
        'chiếc',
        1,
        'Charm treo hình trái tim thuộc bộ sưu tập Pandora Moments, nhẹ nhàng và lãng mạn.',
        NOW(), NOW(), NULL, 3, 5, 11, 2),
    (
        15,
        'Charm Treo Ngôi Sao Disney',
        950000,
        1290000,
        2.30,
        17,
        1,
        40,
        'chiếc',
        1,
        'Charm treo ngôi sao Disney lấp lánh, mang cảm hứng cổ tích.',
        NOW(), NOW(), NULL, 3, 5, 6, 2),
    (
        16,
        'Charm Treo Biểu Tượng Marvel',
        980000,
        1390000,
        2.50,
        17,
        1,
        35,
        'chiếc',
        1,
        'Charm treo biểu tượng Marvel, cá tính và mạnh mẽ.',
        NOW(), NOW(), NULL, 3, 5, 7, 2),
    (
        17,
        'Charm Treo Cung Hoàng Đạo Song Ngư',
        920000,
        1250000,
        2.20,
        17,
        1,
        45,
        'chiếc',
        1,
        'Charm treo cung hoàng đạo Song Ngư, tinh tế và mang ý nghĩa cá nhân.',
        NOW(), NOW(), NULL, 3, 5, 1, 2),
    -- DANH MUC 3 - LOAI 6 charm bấm
    (
        18,
        'Charm Bấm Pandora Signature',
        1100000,
        1490000,
        3.10,
        17,
        1,
        30,
        'chiếc',
        1,
        'Charm bấm Pandora Signature, giúp cố định charm an toàn và chắc chắn.',
        NOW(), NOW(), NULL, 3, 6, 12, 2),
    (
        19,
        'Charm Bấm Trái Tim Unicef',
        1050000,
        1450000,
        3.00,
        17,
        1,
        25,
        'chiếc',
        1,
        'Charm bấm hình trái tim thuộc bộ Unicef x Pandora, mang ý nghĩa nhân văn.',
        NOW(), NOW(), NULL, 3, 6, 4, 2),
    (
        20,
        'Charm Bấm Vương Miện',
        1150000,
        1590000,
        3.20,
        17,
        1,
        20,
        'chiếc',
        1,
        'Charm bấm vương miện sang trọng, điểm nhấn quý phái cho vòng charm.',
        NOW(), NOW(), NULL, 3, 6, 10, 2),
    (
        21,
        'Charm Bấm Pandora Moments',
        1000000,
        1390000,
        3.00,
        17,
        1,
        35,
        'chiếc',
        1,
        'Charm bấm tròn Pandora Moments, giữ charm ổn định khi sử dụng.',
        NOW(), NOW(), NULL, 3, 6, 11, 2),
    (
        22,
        'Charm Thủy Tinh Hoa Sen',
        950000,
        1290000,
        2.40,
        17,
        1,
        40,
        'chiếc',
        1,
        'Charm thủy tinh hoa sen, tôn vinh vẻ đẹp truyền thống Việt.',
        NOW(), NOW(), NULL, 3, 7, 8, 2),
    (
        23,
        'Charm Thủy Tinh Lá Cây',
        980000,
        1350000,
        2.60,
        17,
        1,
        35,
        'chiếc',
        1,
        'Charm thủy tinh hình lá cây, phong cách thiên nhiên nhẹ nhàng.',
        NOW(), NOW(), NULL, 3, 7, 14, 2),
    (
        24,
        'Charm Thủy Tinh Trăng Sao',
        990000,
        1390000,
        2.70,
        17,
        1,
        30,
        'chiếc',
        1,
        'Charm thủy tinh trăng sao, lung linh và huyền ảo.',
        NOW(), NOW(), NULL, 3, 7, 9, 2),
    (
        25,
        'Charm Thủy Tinh Mickey',
        1100000,
        1490000,
        2.80,
        17,
        1,
        25,
        'chiếc',
        1,
        'Charm thủy tinh Mickey Mouse, dễ thương và trẻ trung.',
        NOW(), NOW(), NULL, 3, 7, 6, 2),
    (
        26,
        'Charm Đính Đá Game of Thrones',
        1300000,
        1790000,
        3.50,
        17,
        1,
        20,
        'chiếc',
        1,
        'Charm đính đá lấy cảm hứng Game of Thrones, mạnh mẽ và huyền thoại.',
        NOW(), NOW(), NULL, 3, 8, 5, 2),
    (
        27,
        'Charm Đính Đá Stranger Things',
        1250000,
        1690000,
        3.40,
        17,
        1,
        20,
        'chiếc',
        1,
        'Charm đính đá Stranger Things, thiết kế độc lạ và cá tính.',
        NOW(), NOW(), NULL, 3, 8, 3, 2),
    (
        28,
        'Charm Đính Đá Marvel Limited',
        1350000,
        1890000,
        3.60,
        17,
        1,
        15,
        'chiếc',
        1,
        'Charm đính đá Marvel phiên bản giới hạn, sáng chói và quyền lực.',
        NOW(), NOW(), NULL, 3, 8, 7, 2),
    (
        29,
        'Charm Đính Đá Pandora Signature',
        1400000,
        1950000,
        3.80,
        17,
        1,
        15,
        'chiếc',
        1,
        'Charm đính đá Pandora Signature, cao cấp và sang-xịn-mịn.',
        NOW(), NOW(), NULL, 3, 8, 12, 2),
    (
        30,
        'Dây Chuyền Bạc Pandora Moments Trái Tim',
        2500000,
        2890000,
        6.50,
        45,
        1,
        25,
        'chiếc',
        1,
        'Dây chuyền bạc Pandora Moments với mặt trái tim tinh tế, biểu tượng của tình yêu và sự gắn kết.',
        NOW(), NOW(), NULL, 4, 9, 11, 2),
    (
        31,
        'Dây Chuyền Bạc Pandora Timeless Đính Đá',
        3200000,
        3590000,
        6.80,
        45,
        1,
        20,
        'chiếc',
        1,
        'Dây chuyền bạc thuộc bộ Pandora Timeless, điểm xuyết đá zirconia sang trọng.',
        NOW(), NOW(), NULL, 4, 9, 13, 2),
    (
        32,
        'Dây Chuyền Bạc Disney Mickey',
        2800000,
        3190000,
        6.20,
        45,
        1,
        30,
        'chiếc',
        1,
        'Dây chuyền bạc Disney x Pandora với mặt Mickey dễ thương và trẻ trung.',
        NOW(), NOW(), NULL, 4, 9, 6, 2),
    (
        33,
        'Dây Chuyền Bạc Cung Hoàng Đạo Xử Nữ',
        2600000,
        2990000,
        6.40,
        45,
        1,
        25,
        'chiếc',
        1,
        'Dây chuyền bạc cung hoàng đạo Xử Nữ thuộc bộ Zodiac Signs, tinh tế và cá tính.',
        NOW(), NOW(), NULL, 4, 9, 1, 2),
    (
        34,
        'Dây Chuyền Bạc Pandora Signature Logo O',
        3000000,
        3390000,
        6.90,
        45,
        1,
        20,
        'chiếc',
        1,
        'Dây chuyền bạc Pandora Signature với biểu tượng Crown O tối giản và sang trọng.',
        NOW(), NOW(), NULL, 4, 9, 12, 2),
    (
        35,
        'Dây Chuyền Mạ Vàng Pandora Signature',
        4200000,
        4690000,
        7.20,
        45,
        1,
        15,
        'chiếc',
        1,
        'Dây chuyền mạ vàng Pandora Signature mang phong cách hiện đại và cao cấp.',
        NOW(), NOW(), NULL, 4, 10, 12, 2),
    (
        36,
        'Dây Chuyền Mạ Vàng Trái Tim Unicef',
        4000000,
        4490000,
        7.10,
        45,
        1,
        15,
        'chiếc',
        1,
        'Dây chuyền mạ vàng thuộc bộ Unicef x Pandora, mang thông điệp nhân văn.',
        NOW(), NOW(), NULL, 4, 10, 4, 2),
    (
        37,
        'Dây Chuyền Mạ Vàng Disney Princess',
        3900000,
        4390000,
        7.00,
        45,
        1,
        20,
        'chiếc',
        1,
        'Dây chuyền mạ vàng Disney x Pandora lấy cảm hứng từ các nàng công chúa.',
        NOW(), NOW(), NULL, 4, 10, 6, 2),
    (
        38,
        'Dây Chuyền Mạ Vàng Vương Quyền',
        4500000,
        4990000,
        7.50,
        45,
        1,
        10,
        'chiếc',
        1,
        'Dây chuyền mạ vàng thuộc bộ Vương Quyền, thiết kế mạnh mẽ và sang trọng.',
        NOW(), NOW(), NULL, 4, 10, 10, 2),
    (
        39,
        'Dây Chuyền Mạ Vàng Thiên Nhiên Lá Cây',
        3800000,
        4290000,
        6.90,
        45,
        1,
        20,
        'chiếc',
        1,
        'Dây chuyền mạ vàng lấy cảm hứng từ thiên nhiên, nhẹ nhàng và tinh tế.',
        NOW(), NOW(), NULL, 4, 10, 9, 2),
    (
        40,
        'Dây Chuyền Mạ Vàng Hồng Pandora Signature',
        4600000,
        5190000,
        7.30,
        45,
        1,
        15,
        'chiếc',
        1,
        'Dây chuyền mạ vàng hồng Pandora Signature, gam màu ấm áp và sang trọng.',
        NOW(), NOW(), NULL, 4, 11, 12, 2),
    (
        41,
        'Dây Chuyền Mạ Vàng Hồng Tim Halo Timeless',
        4800000,
        5390000,
        7.40,
        45,
        1,
        10,
        'chiếc',
        1,
        'Dây chuyền mạ vàng hồng Timeless với mặt tim Halo đính đá lấp lánh.',
        NOW(), NOW(), NULL, 4, 11, 13, 2),
    (
        42,
        'Dây Chuyền Mạ Vàng Hồng Disney Minnie',
        4300000,
        4890000,
        7.10,
        45,
        1,
        20,
        'chiếc',
        1,
        'Dây chuyền mạ vàng hồng Disney x Pandora với mặt Minnie ngọt ngào.',
        NOW(), NOW(), NULL, 4, 11, 6, 2),
    (
        43,
        'Dây Chuyền Mạ Vàng Hồng Thiên Nhiên Hoa',
        4100000,
        4590000,
        7.00,
        45,
        1,
        20,
        'chiếc',
        1,
        'Dây chuyền mạ vàng hồng lấy cảm hứng từ hoa lá thiên nhiên.',
        NOW(), NOW(), NULL, 4, 11, 14, 2),
    (
        44,
        'Dây Chuyền Mạ Vàng Hồng Pandora Necklace',
        4400000,
        4990000,
        7.20,
        45,
        1,
        15,
        'chiếc',
        1,
        'Dây chuyền mạ vàng hồng thuộc bộ Pandora Necklace, thiết kế thanh lịch và dễ phối.',
        NOW(), NOW(), NULL, 4, 11, 15, 2),
    (
        45,
        'Hoa Tai Tròn Bạc Pandora Signature',
        2200000,
        2590000,
        3.20,
        2,
        1,
        30,
        'đôi',
        1,
        'Hoa tai tròn bạc thuộc bộ Pandora Signature, thiết kế tối giản và hiện đại.',
        NOW(), NOW(), NULL, 5, 12, 12, 2),
    (
        46,
        'Hoa Tai Tròn Bạc Pandora Signature',
        2400000,
        2790000,
        3.40,
        2,
        1,
        25,
        'đôi',
        1,
        'Hoa tai tròn Disney x Pandora với biểu tượng Mickey dễ thương.',
        NOW(), NOW(), NULL, 5, 12, 6, 2),
    (
        47,
        'Hoa Tai Tròn Tim Halo Timeless',
        2600000,
        2990000,
        3.60,
        2,
        1,
        20,
        'đôi',
        1,
        'Hoa tai tròn Timeless với đá halo lấp lánh, sang xịn mịn.',
        NOW(), NOW(), NULL, 5, 12, 13, 2),
    (
        48,
        'Hoa Tai Tròn Cung Hoàng Đạo Song Ngư',
        2300000,
        2690000,
        3.30,
        2,
        1,
        20,
        'đôi',
        1,
        'Hoa tai tròn cung Song Ngư thuộc bộ Zodiac Signs, nhẹ nhàng và tinh tế.',
        NOW(), NOW(), NULL, 5, 12, 1, 2),
    (
        49,
        'Hoa Tai Tròn Thiên Nhiên Lá',
        2100000,
        2490000,
        3.10,
        2,
        1,
        25,
        'đôi',
        1,
        'Hoa tai tròn lấy cảm hứng từ thiên nhiên, phù hợp phong cách daily.',
        NOW(), NOW(), NULL, 5, 12, 9, 2),
    (
        50,
        'Hoa Tai Ngọc Trai Pandora Timeless',
        2800000,
        3290000,
        3.80,
        3,
        1,
        20,
        'đôi',
        1,
        'Hoa tai ngọc trai thuộc bộ Timeless, thanh lịch và nữ tính.',
        NOW(), NOW(), NULL, 5, 13, 13, 2),
    (
        51,
        'Hoa Tai Ngọc Trai Mạ Vàng Signature',
        3000000,
        3490000,
        4.00,
        3,
        1,
        15,
        'đôi',
        1,
        'Hoa tai ngọc trai mạ vàng Pandora Signature, sang trọng và tinh tế.',
        NOW(), NOW(), NULL, 5, 13, 12, 2),
    (
        52,
        'Hoa Tai Ngọc Trai Disney Princess',
        2900000,
        3390000,
        3.90,
        3,
        1,
        20,
        'đôi',
        1,
        'Hoa tai ngọc trai Disney x Pandora, lấy cảm hứng từ công chúa.',
        NOW(), NOW(), NULL, 5, 13, 6, 2),
    (
        53,
        'Hoa Tai Ngọc Trai Thiên Nhiên',
        2700000,
        3190000,
        3.70,
        3,
        1,
        20,
        'đôi',
        1,
        'Hoa tai ngọc trai mang phong cách thiên nhiên, nhẹ nhàng và tinh khôi.',
        NOW(), NOW(), NULL, 5, 13, 9, 2),
    (
        54,
        'Hoa Tai Ngọc Trai Vương Quyền',
        3200000,
        3690000,
        4.20,
        3,
        1,
        10,
        'đôi',
        1,
        'Hoa tai ngọc trai thuộc bộ Vương Quyền, phong cách quý phái.',
        NOW(), NOW(), NULL, 5, 13, 10, 2),
    (
        55,
        'Hoa Tai Rơi Bạc Pandora Moments',
        2500000,
        2890000,
        4.50,
        4,
        1,
        25,
        'đôi',
        1,
        'Hoa tai rơi bạc Pandora Moments, chuyển động nhẹ nhàng và cuốn hút.',
        NOW(), NOW(), NULL, 5, 14, 11, 2),
    (
        56,
        'Hoa Tai Rơi Tim Halo Timeless',
        2900000,
        3390000,
        4.80,
        4,
        1,
        20,
        'đôi',
        1,
        'Hoa tai rơi Timeless với thiết kế halo sang trọng.',
        NOW(), NOW(), NULL, 5, 14, 13, 2),
    (
        57,
        'Hoa Tai Rơi Disney Minnie',
        2700000,
        3190000,
        4.60,
        4,
        1,
        20,
        'đôi',
        1,
        'Hoa tai rơi Disney x Pandora với biểu tượng Minnie đáng yêu.',
        NOW(), NOW(), NULL, 5, 14, 6, 2),
    (
        58,
        'Hoa Tai Rơi Mạ Vàng Hồng Signature',
        3100000,
        3590000,
        5.00,
        4,
        1,
        15,
        'đôi',
        1,
        'Hoa tai rơi mạ vàng hồng Pandora Signature, tôn da cực xịn.',
        NOW(), NOW(), NULL, 5, 14, 12, 2),
    (
        59,
        'Hoa Tai Rơi Thiên Nhiên Hoa',
        2600000,
        3090000,
        4.70,
        4,
        1,
        20,
        'đôi',
        1,
        'Hoa tai rơi lấy cảm hứng từ hoa lá thiên nhiên, nhẹ nhàng và nữ tính.',
        NOW(), NOW(), NULL, 5, 14, 9, 2),
    (
        60,
        'Nhẫn Mạ Bạc Pandora Signature',
        1800000,
        2190000,
        2.30,
        7,
        1,
        30,
        'chiếc',
        1,
        'Nhẫn mạ bạc Pandora Signature với thiết kế tối giản và hiện đại.',
        NOW(), NOW(), NULL, 6, 15, 12, 2),
    (
        61,
        'Nhẫn Mạ Bạc Tim Halo Timeless',
        2000000,
        2390000,
        2.50,
        7,
        1,
        25,
        'chiếc',
        1,
        'Nhẫn mạ bạc Timeless với điểm nhấn halo tinh xảo.',
        NOW(), NOW(), NULL, 6, 15, 13, 2),
    (
        62,
        'Nhẫn Mạ Bạc Cung Hoàng Đạo Bạch Dương',
        1900000,
        2290000,
        2.40,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ bạc Zodiac Signs dành cho cung Bạch Dương cá tính.',
        NOW(), NOW(), NULL, 6, 15, 1, 2),
    (
        63,
        'Nhẫn Mạ Bạc Disney Minnie',
        2100000,
        2490000,
        2.60,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ bạc Disney x Pandora với biểu tượng Minnie đáng yêu.',
        NOW(), NOW(), NULL, 6, 15, 6, 2),
    (
        64,
        'Nhẫn Mạ Bạc Thiên Nhiên Lá',
        1850000,
        2250000,
        2.35,
        7,
        1,
        25,
        'chiếc',
        1,
        'Nhẫn mạ bạc lấy cảm hứng từ thiên nhiên, nhẹ nhàng và tinh tế.',
        NOW(), NOW(), NULL, 6, 15, 9, 2),
    (
        65,
        'Nhẫn Mạ Vàng Pandora Signature',
        2400000,
        2890000,
        2.80,
        7,
        1,
        25,
        'chiếc',
        1,
        'Nhẫn mạ vàng Pandora Signature mang phong cách sang trọng.',
        NOW(), NOW(), NULL, 6, 16, 12, 2),
    (
        66,
        'Nhẫn Mạ Vàng Tim Timeless',
        2600000,
        3090000,
        3.00,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ vàng Timeless với biểu tượng trái tim tinh xảo.',
        NOW(), NOW(), NULL, 6, 16, 13, 2),
    (
        67,
        'Nhẫn Mạ Vàng Disney Princess',
        2500000,
        2990000,
        2.90,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ vàng Disney x Pandora lấy cảm hứng từ công chúa.',
        NOW(), NOW(), NULL, 6, 16, 6, 2),
    (
        68,
        'Nhẫn Mạ Vàng Vương Quyền',
        2800000,
        3290000,
        3.20,
        7,
        1,
        15,
        'chiếc',
        1,
        'Nhẫn mạ vàng thuộc bộ Vương Quyền, phong cách quyền lực.',
        NOW(), NOW(), NULL, 6, 16, 10, 2),
    (
        69,
        'Nhẫn Mạ Vàng Thiên Nhiên Hoa',
        2450000,
        2950000,
        2.85,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ vàng thiết kế hoa lá thiên nhiên dịu dàng.',
        NOW(), NOW(), NULL, 6, 16, 9, 2),
    (
        70,
        'Nhẫn Mạ Vàng Hồng Pandora Signature',
        2600000,
        3090000,
        2.90,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ vàng hồng Pandora Signature, tôn da và cực trendy.',
        NOW(), NOW(), NULL, 6, 17, 12, 2),
    (
        71,
        'Nhẫn Mạ Vàng Hồng Tim Halo Timeless',
        2800000,
        3290000,
        3.10,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ vàng hồng Timeless với đá halo lấp lánh.',
        NOW(), NOW(), NULL, 6, 17, 13, 2),
    (
        72,
        'Nhẫn Mạ Vàng Hồng Disney Minnie',
        2700000,
        3190000,
        3.00,
        7,
        1,
        15,
        'chiếc',
        1,
        'Nhẫn mạ vàng hồng Disney Minnie, dễ thương mà vẫn sang.',
        NOW(), NOW(), NULL, 6, 17, 6, 2),
    (
        73,
        'Nhẫn Mạ Vàng Hồng Thiên Nhiên',
        2550000,
        3050000,
        2.95,
        7,
        1,
        20,
        'chiếc',
        1,
        'Nhẫn mạ vàng hồng lấy cảm hứng từ thiên nhiên mềm mại.',
        NOW(), NOW(), NULL, 6, 17, 9, 2),
    (
        74,
        'Nhẫn Mạ Vàng Hồng Vương Quyền',
        2900000,
        3390000,
        3.30,
        7,
        1,
        10,
        'chiếc',
        1,
        'Nhẫn mạ vàng hồng Vương Quyền – đeo vô là thấy quyền lực liền.',
        NOW(), NOW(), NULL, 6, 17, 10, 2);
