"""init all schemas

Revision ID: 562662d40c3f
Revises: 
Create Date: 2026-01-19 12:54:04.843167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562662d40c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BoSuuTap',
    sa.Column('ma_bo_suu_tap', sa.Integer(), nullable=False),
    sa.Column('ten_bo_suu_tap', sa.String(length=256), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('ma_bo_suu_tap')
    )
    op.create_table('ChatLieu',
    sa.Column('ma_chat_lieu', sa.Integer(), nullable=False),
    sa.Column('ten_chat_lieu', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('ma_chat_lieu')
    )
    op.create_table('DanhMuc',
    sa.Column('ma_danh_muc', sa.Integer(), nullable=False),
    sa.Column('ten_danh_muc', sa.String(length=256), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('ma_danh_muc')
    )
    op.create_table('KichThuocSanPham',
    sa.Column('ma_kich_thuoc_san_pham', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('ten_kich_thuoc', sa.Float(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ma_kich_thuoc_san_pham')
    )
    op.create_table('TaiKhoan',
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=False),
    sa.Column('ten_tai_khoan', sa.String(length=256), nullable=False),
    sa.Column('mat_khau', sa.String(length=256), nullable=False),
    sa.Column('ho_ten', sa.String(length=256), nullable=False),
    sa.Column('ngay_sinh', sa.DateTime(), nullable=False),
    sa.Column('gioi_tinh', sa.SmallInteger(), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('dia_chi', sa.String(length=256), nullable=False),
    sa.Column('trang_thai', sa.SmallInteger(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('ma_tai_khoan')
    )
    op.create_table('ThuongHieu',
    sa.Column('ma_thuong_hieu', sa.Integer(), nullable=False),
    sa.Column('ten_thuong_hieu', sa.String(length=256), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('dia_chi', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('ma_thuong_hieu')
    )
    op.create_table('DonHang',
    sa.Column('ma_don_hang', sa.Integer(), nullable=False),
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=False),
    sa.Column('tong_tien_tam_tinh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ma_tai_khoan'], ['TaiKhoan.ma_tai_khoan'], ),
    sa.PrimaryKeyConstraint('ma_don_hang')
    )
    op.create_table('GioHang',
    sa.Column('ma_gio_hang', sa.Integer(), nullable=False),
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_tai_khoan'], ['TaiKhoan.ma_tai_khoan'], ),
    sa.PrimaryKeyConstraint('ma_gio_hang')
    )
    op.create_table('HoaDon',
    sa.Column('ma_hoa_don', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_tai_khoan', sa.Integer(), nullable=False),
    sa.Column('tong_tien_tam_tinh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_dat_hang', sa.DateTime(), nullable=True),
    sa.Column('trang_thai', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ma_tai_khoan'], ['TaiKhoan.ma_tai_khoan'], ),
    sa.PrimaryKeyConstraint('ma_hoa_don')
    )
    op.create_table('LoaiSanPham',
    sa.Column('ma_loai_san_pham', sa.Integer(), nullable=False),
    sa.Column('ten_loai_san_pham', sa.String(length=256), nullable=False),
    sa.Column('ma_danh_muc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_danh_muc'], ['DanhMuc.ma_danh_muc'], ),
    sa.PrimaryKeyConstraint('ma_loai_san_pham')
    )
    op.create_table('SanPham',
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('ten_san_pham', sa.String(length=256), nullable=False),
    sa.Column('gia_nhap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gia_xuat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trong_luong', sa.Float(), nullable=False),
    sa.Column('gioi_tinh', sa.SmallInteger(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('don_vi_tinh', sa.String(length=256), nullable=False),
    sa.Column('trang_thai', sa.SmallInteger(), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_chinh_sua', sa.DateTime(), nullable=True),
    sa.Column('ma_danh_muc', sa.Integer(), nullable=True),
    sa.Column('ma_loai_san_pham', sa.Integer(), nullable=True),
    sa.Column('ma_bo_suu_tap', sa.Integer(), nullable=True),
    sa.Column('ma_thuong_hieu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ma_bo_suu_tap'], ['BoSuuTap.ma_bo_suu_tap'], ),
    sa.ForeignKeyConstraint(['ma_danh_muc'], ['DanhMuc.ma_danh_muc'], ),
    sa.ForeignKeyConstraint(['ma_loai_san_pham'], ['LoaiSanPham.ma_loai_san_pham'], ),
    sa.ForeignKeyConstraint(['ma_thuong_hieu'], ['ThuongHieu.ma_thuong_hieu'], ),
    sa.PrimaryKeyConstraint('ma_san_pham')
    )
    op.create_table('ChiTietDonHang',
    sa.Column('ma_chi_tiet_don_hang', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_don_hang'], ['DonHang.ma_don_hang'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['SanPham.ma_san_pham'], ),
    sa.PrimaryKeyConstraint('ma_chi_tiet_don_hang')
    )
    op.create_table('ChiTietGioHang',
    sa.Column('ma_chi_tiet_gio_hang', sa.Integer(), nullable=False),
    sa.Column('ma_gio_hang', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_gio_hang'], ['GioHang.ma_gio_hang'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['SanPham.ma_san_pham'], ),
    sa.PrimaryKeyConstraint('ma_chi_tiet_gio_hang')
    )
    op.create_table('ChiTietHoaDon',
    sa.Column('ma_chi_tiet_hoa_don', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_hoa_don', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('don_gia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thanh_tien', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ma_hoa_don'], ['HoaDon.ma_hoa_don'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['SanPham.ma_san_pham'], ),
    sa.PrimaryKeyConstraint('ma_chi_tiet_hoa_don')
    )
    op.create_table('DanhGia',
    sa.Column('ma_danh_gia', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('nguoi_danh_gia', sa.Integer(), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['SanPham.ma_san_pham'], ),
    sa.ForeignKeyConstraint(['nguoi_danh_gia'], ['TaiKhoan.ma_tai_khoan'], ),
    sa.PrimaryKeyConstraint('ma_danh_gia')
    )
    op.create_table('HinhAnhSanPham',
    sa.Column('ma_hinh_anh', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('duong_dan', sa.String(length=256), nullable=False),
    sa.Column('anh_chinh', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['SanPham.ma_san_pham'], ),
    sa.PrimaryKeyConstraint('ma_hinh_anh')
    )
    op.create_table('SanPham__ChatLieu',
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('ma_chat_lieu', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_chat_lieu'], ['ChatLieu.ma_chat_lieu'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['SanPham.ma_san_pham'], ),
    sa.PrimaryKeyConstraint('ma_san_pham', 'ma_chat_lieu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SanPham__ChatLieu')
    op.drop_table('HinhAnhSanPham')
    op.drop_table('DanhGia')
    op.drop_table('ChiTietHoaDon')
    op.drop_table('ChiTietGioHang')
    op.drop_table('ChiTietDonHang')
    op.drop_table('SanPham')
    op.drop_table('LoaiSanPham')
    op.drop_table('HoaDon')
    op.drop_table('GioHang')
    op.drop_table('DonHang')
    op.drop_table('ThuongHieu')
    op.drop_table('TaiKhoan')
    op.drop_table('KichThuocSanPham')
    op.drop_table('DanhMuc')
    op.drop_table('ChatLieu')
    op.drop_table('BoSuuTap')
    # ### end Alembic commands ###
